### ISSUE TITLE
Installation and Running Example problems

### ISSUE THREAD

**Issue by GregorySchwing** [dtqec/anatevka#41]
I installed sbcl and quicklisp.  I am installing "aether" and "anatevka" using quicklisp.  

I load anatevka and aether using quicklisp

0] (ql:quickload "anatevka")
To load "anatevka":
  Load 1 ASDF system:
    anatevka
; Loading "anatevka"

("anatevka")

0[2] (ql:quickload "aether")
To load "aether":
  Load 1 ASDF system:
    aether
; Loading "aether"

("aether")

Then I past the code boxes from the readme into sbcl.

0[2] (defstruct demo-id
  "A wrapper for a vertex ID used in the Mathematica blossom demo."
  (value nil :type (integer 1 8)))

(defmethod anatevka::vertex-vertex-distance ((id-v demo-id) (id-w demo-id))
  (let ((v (demo-id-value id-v))
        (w (demo-id-value id-w)))
    ;; index into the following weighted adjacency matrix
    (aref #2A(( 0 40 52 50 46 70 36 46)
              (40  0 34 54 28 64 20  6)
              (52 34  0 28 34 24  2 30)
              (50 54 28  0 42 18 36  8)
              (46 28 34 42  0 14 80 22)
              (70 64 24 18 14  0 22 64)
              (36 20  2 36 80 22  0 80)
              (46  6 30  8 22 64 80  0))
          (1- v) (1- w))))
DEMO-ID
0[2] 

#<STANDARD-METHOD ANATEVKA:VERTEX-VERTEX-DISTANCE (DEMO-ID DEMO-ID) {1001A42053}>

0[2] (let* ((simulation (make-simulation))
       ;; aether requires us to bind `*local-courier*' before spawning processes.
       (*local-courier* (make-courier :processing-clock-rate 300))
       ;; The edges discovered by the algorithm will be announced on this address.
       (match-address (register))
       ;; This process manages graph discovery.
       (dryad (spawn-process 'dryad
                             :process-clock-rate 20
                             :debug? t
                             :match-address match-address)))
  ;; Set up the core simulation components: the network host and the dryad.
  (simulation-add-event simulation
                        (make-event :callback *local-courier* :time 0))
  (simulation-add-event simulation (make-event :callback dryad :time 0))
  ;; Prime the dryad with messages to spawn workers for the eight vertices.
  (loop :for j :from 1 :to 8
        :for id := (make-demo-id :value j)
        :do (send-message (process-public-address dryad)
                          (anatevka::make-message-sow :id id)))
  ;; Run simulation until maximally matched (i.e., until the dryad terminates).
  (simulation-run simulation :canary (canary-process dryad))
  ;; Read out the match edges from the `match-address' mailbox.
  (labels ((drain-match-address (&optional acc)
             (receive-message (match-address message)
               (message-reap
                (drain-match-address (list* (message-reap-ids message) acc)))
               (otherwise
                acc))))
    
    ;; Calculate the weight of the matching.
    (loop :for (left right) :in (drain-match-address)
          :do (format t "~d --~02d-- ~d~%"
                      (demo-id-value left)
                      (vertex-vertex-distance left right)
                      (demo-id-value right))
          :sum (anatevka::vertex-vertex-distance left right))))
; in: LAMBDA (#:G476)
;     (LET* ((SIMULATION (MAKE-SIMULATION))
;            (*LOCAL-COURIER* (MAKE-COURIER :PROCESSING-CLOCK-RATE 300))
;            (MATCH-ADDRESS (REGISTER))
;            (DRYAD
;             (SPAWN-PROCESS 'DRYAD :PROCESS-CLOCK-RATE 20 :DEBUG? T :MATCH-ADDRESS
;              MATCH-ADDRESS)))
;       (SIMULATION-ADD-EVENT SIMULATION
;        (MAKE-EVENT :CALLBACK *LOCAL-COURIER* :TIME 0))
;       (SIMULATION-ADD-EVENT SIMULATION (MAKE-EVENT :CALLBACK DRYAD :TIME 0))
;       (LOOP :FOR J :FROM 1 :TO 8
;             :FOR ID := (MAKE-DEMO-ID :VALUE J)
;             :DO ...)
;       (SIMULATION-RUN SIMULATION :CANARY (CANARY-PROCESS DRYAD))
;       (LABELS ((DRAIN-MATCH-ADDRESS (&OPTIONAL ACC)
;                  (RECEIVE-MESSAGE # # #)))
;         (LOOP :FOR (LEFT RIGHT) :IN (DRAIN-MATCH-ADDRESS)
;               :DO (FORMAT T "~d --~02d-- ~d~%" (DEMO-ID-VALUE LEFT)
;                           (VERTEX-VERTEX-DISTANCE LEFT RIGHT)
;                           (DEMO-ID-VALUE RIGHT))
;               :SUM (ANATEVKA:VERTEX-VERTEX-DISTANCE LEFT RIGHT))))
; 
; caught STYLE-WARNING:
;   using the lexical binding of the symbol (COMMON-LISP-USER::*LOCAL-COURIER*), not the
;   dynamic binding, even though the name follows
;   the usual naming convention (names like *FOO*) for special variables
; in: LAMBDA (#:G476)
;     (CANARY-PROCESS DRYAD)
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::CANARY-PROCESS

;     (MAKE-COURIER :PROCESSING-CLOCK-RATE 300)
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::MAKE-COURIER

;     (MAKE-EVENT :CALLBACK *LOCAL-COURIER* :TIME 0)
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::MAKE-EVENT

;     (MAKE-SIMULATION)
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::MAKE-SIMULATION

;     (MATCH-ADDRESS MESSAGE)
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::MATCH-ADDRESS
; 
; caught WARNING:
;   undefined variable: COMMON-LISP-USER::MESSAGE

;     (MESSAGE-REAP (DRAIN-MATCH-ADDRESS (LIST* (MESSAGE-REAP-IDS MESSAGE) ACC)))
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::MESSAGE-REAP

;     (MESSAGE-REAP-IDS MESSAGE)
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::MESSAGE-REAP-IDS

;     (OTHERWISE ACC)
; 
; caught WARNING:
;   The function OTHERWISE is undefined, and its name is reserved by ANSI CL so
;   that even if it were defined later, the code doing so would not be portable.

;     (PROCESS-PUBLIC-ADDRESS DRYAD)
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::PROCESS-PUBLIC-ADDRESS

;     (RECEIVE-MESSAGE (MATCH-ADDRESS MESSAGE)
;      (MESSAGE-REAP (DRAIN-MATCH-ADDRESS (LIST* (MESSAGE-REAP-IDS MESSAGE) ACC)))
;      (OTHERWISE ACC))
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::RECEIVE-MESSAGE

;     (REGISTER)
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::REGISTER

;     (SEND-MESSAGE (PROCESS-PUBLIC-ADDRESS DRYAD)
;      (ANATEVKA:MAKE-MESSAGE-SOW :ID ID))
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::SEND-MESSAGE

;     (SIMULATION-ADD-EVENT SIMULATION
;      (MAKE-EVENT :CALLBACK *LOCAL-COURIER* :TIME 0))
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::SIMULATION-ADD-EVENT

;     (SIMULATION-RUN SIMULATION :CANARY (CANARY-PROCESS DRYAD))
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::SIMULATION-RUN

;     (SPAWN-PROCESS 'DRYAD :PROCESS-CLOCK-RATE 20 :DEBUG? T :MATCH-ADDRESS
;      MATCH-ADDRESS)
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::SPAWN-PROCESS

;     (VERTEX-VERTEX-DISTANCE LEFT RIGHT)
; 
; caught STYLE-WARNING:
;   undefined function: COMMON-LISP-USER::VERTEX-VERTEX-DISTANCE
; 
; compilation unit finished
;   Undefined functions:
;     CANARY-PROCESS MAKE-COURIER MAKE-EVENT MAKE-SIMULATION MATCH-ADDRESS MESSAGE-REAP MESSAGE-REAP-IDS OTHERWISE PROCESS-PUBLIC-ADDRESS RECEIVE-MESSAGE REGISTER SEND-MESSAGE SIMULATION-ADD-EVENT SIMULATION-RUN SPAWN-PROCESS VERTEX-VERTEX-DISTANCE
;   Undefined variable:
;     MESSAGE
;   caught 2 WARNING conditions
;   caught 16 STYLE-WARNING conditions

debugger invoked on a UNDEFINED-FUNCTION in thread
#<THREAD "main thread" RUNNING {1000560083}>:
  The function COMMON-LISP-USER::MAKE-SIMULATION is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE      ] Retry calling MAKE-SIMULATION.
  1: [USE-VALUE     ] Call specified function.
  2: [RETURN-VALUE  ] Return specified values.
  3: [RETURN-NOTHING] Return zero values.
  4: [ABORT         ] Reduce debugger level (to debug level 2).
  5:                  Reduce debugger level (to debug level 1).
  6:                  Exit debugger, returning to top level.

("undefined function")
0[3]

**Comment by ecpeterson** [comment]
Ah, good catch: the example in the README expects to use a bunch of things from the `anatevka` package, but doesn't qualify those names or tell you to change your active package. After quickloading, and before executing the sample code in the README (including the `defstruct`), run the following command:

```lisp
(in-package #:anatevka)
```

(Alternatively, one can go through and sprinkle `anatevka:` before many of the symbols, but this is strictly more work.)

**Comment by GregorySchwing** [comment]
Thank you.
